export type Testimonial = {
  name: string;
  role: string;
  company: string;
  quote: string;
  avatar: string;
  rating: number;
};

export type CountryWithCities = {
  name: string;
  cities: string[];
};

export const POST_LOAD = {
  form: {
    title: "Quick Load Post",
    description: "Share your load details and we'll match you with the best carriers.",
    submitButton: "Post Load",
    submitAlert: "Load submitted! Check console for payload.",
    submitConsoleMessage: "Submitting load",
  },

  sections: {
    locationDetails: "Location Details",
    loadDetails: "Load Details",
  },

  labels: {
    sourceCountry: "Source Country",
    destinationCountry: "Destination Country",
    weight: "Weight (kg)",
    loadType: "Load Type",
    materialType: "Material Type",
    scheduledDate: "Scheduled Date",
    hsnCode: "Material HSN Code (Optional)",
  },

  placeholders: {
    selectCountry: "Select country",
    selectType: "Select type",
    materialTypeExample: "e.g., Steel Coils",
    hsnCodeExample: "e.g., 7208",
  },

  ariaLabels: {
    customerTestimonials: "Customer testimonials",
    previousReview: "Previous review",
    nextReview: "Next review",
    avatar: "Avatar",
    goToReview: "Go to review",
  },

  alt: {
    texture: "texture",
  },

  data: {
    countries: [
      {
        name: "Bahrain",
        cities: [
          "Manama",
          "Muharraq",
          "Hamad Town",
          "Riffa",
          "A'ali",
          "Sitra",
          "Jidhafs",
          "Isa Town",
          "Budaiya",
          "Diraz",
        ],
      },
      {
        name: "Kuwait",
        cities: [
          "Kuwait City",
          "Al Jahrā",
          "Abū Ḩulayfah",
          "Al Aḩmadī",
          "Ar Riqqah",
          "Al Bida",
          "Al Farwānīyah",
          "Al Udaylīyah",
          "Abraq Khayţān",
          "Al Abbāsīyah",
          "Ash Shadādīyah",
          "An Nijfah",
          "Al Quşūr",
          "Mishrif",
          "Al Massīlah",
          "Al Funayţīs",
          "Aş Şabāḩīyah",
          "Duwaydāt",
          "Juaydān",
          "Aţ Ţawīl",
          "Urayfijān",
          "Al Qurayn",
          "Aḑ Ḑibāīyah",
          "Al Maqwa",
          "Al Uqaylah",
          "An Nuqayyāt",
          "Az Zawr",
          "Al Manqaf",
          "Manīfah",
          "Mubārak al Kabīr",
          "Şubayḩīyah",
          "Al Khīrān",
          "Al Mahbūlah",
          "Al Wafrah",
        ],
      },
      {
        name: "Oman",
        cities: [
          "Adam",
          "As Sib",
          "Al Ashkharah",
          "Al Buraimi",
          "Al Hamra",
          "Al Jazer",
          "Al Madina A'Zarqa/Blue City",
          "Al Suwaiq",
          "Bahla",
          "Barka",
          "Bidbid",
          "Bidiya",
          "Duqm",
          "Haima",
          "Ibra",
          "Ibri",
          "Izki",
          "Jabrin",
          "Jalan Bani Bu Hassan",
          "Khasab",
          "Manah",
          "Masirah",
          "Mudhaybi",
          "Mudhaireb",
          "Muscat",
          "Muttrah",
          "Nizwa",
          "Quriyat",
          "Raysut",
          "Rustaq",
          "Ruwi",
          "Saham",
          "Shinas",
          "Saiq",
          "Salalah",
          "Samail",
          "Sohar",
          "Sur",
          "Tan`am",
          "Thumrait",
          "Liwa",
        ],
      },
      {
        name: "Qatar",
        cities: [
          "Abu Dhalouf",
          "Abu Hamour",
          "Abu Samra",
          "Ain Khaled",
          "Ain Sinan",
          "Al Aziziya",
          "Baaya",
          "Bani Hajer",
          "Barahat Al Jufairi",
          "Bu Fasseela",
          "Bu Samra",
          "Bu Sidra",
          "Al Bidda",
          "Dahl Al Hamam",
          "Doha International Airport",
          "Doha Port",
          "Duhail",
          "Dukhan",
          "Al Daayen",
          "Al Dafna",
          "Ad Dawhah al Jadidah",
          "Al Ebb",
          "Al Egla",
          "Fuwayrit",
          "Fereej Abdel Aziz",
          "Fereej Bin Durham",
          "Fereej Bin Mahmoud",
          "Fereej Bin Omran",
          "Fereej Kulaib",
          "Fereej Mohammed Bin Jassim",
          "Fereej Al Amir",
          "Fereej Al Asiri",
          "Fereej Al Asmakh",
          "Fereej Al Murra",
          "Fereej Al Manaseer",
          "Fereej Al Nasr",
          "Fereej Al Soudan",
          "Fereej Al Zaeem",
          "Gharrafat Al Rayyan",
          "Al Gharrafa",
          "Al Ghuwariyah",
          "Hamad Medical City",
          "Hazm Al Markhiya",
          "Al Hilal",
          "Industrial Area",
          "Izghawa (Al Rayyan)",
          "Izghawa (Umm Salal)",
          "Jabal Thuaileb",
          "Jelaiah",
          "Jeryan Jenaihat",
          "Jeryan Nejaima",
          "Al Jasrah",
          "Al Jeryan",
          "Khor Al Adaid",
          "Al Karaana",
          "Al Kharrara",
          "Al Kharaitiyat",
          "Al Kharayej",
          "Al Kheesa",
          "Al Khor",
          "Al Khulaifat",
          "Leabaib",
          "Lebday",
          "Lejbailat",
          "Lekhwair",
          "Leqtaifiya (West Bay Lagoon)",
          "Lijmiliya",
          "Luaib",
          "Lusail",
          "Al Luqta",
          "Madinat ash Shamal",
          "Madinat Al Kaaban",
          "Madinat Khalifa North",
          "Madinat Khalifa South",
          "Mebaireek",
          "Mehairja",
          "Mesaieed",
          "Mesaieed Industrial Area",
          "Mesaimeer",
          "Al Messila",
          "Muaither",
          "Muraikh",
          "Mushayrib",
          "Al Mamoura",
          "Al Mansoura",
          "Al Markhiyah",
          "Al Mashaf",
          "Al Masrouhiya",
          "Al Mearad",
          "Al Mirqab",
          "Najma",
          "New Al Hitmi",
          "New Al Mirqab",
          "New Al Rayyan",
          "New Salata",
          "New Fereej Al Ghanim",
          "New Fereej Al Khulaifat",
          "Nu`ayjah",
          "Al Najada",
          "Al Nasraniya",
          "Old Airport",
          "Old Al Ghanim",
          "Old Al Hitmi",
          "Old Al Rayyan",
          "Onaiza",
          "The Pearl",
          "Al Qassar",
          "Ras Abu Aboud",
          "Ras Lafan",
          "Rawdat Al Hamama",
          "Rawdat Al Khail",
          "Rawdat Egdaim",
          "Rawdat Rashed",
          "Rumeilah",
          "Ar Ru'ays",
          "Al Rufaa",
          "Sawda Natheel",
          "Shagra",
          "Simaisma",
          "Al Sadd",
          "As Salatah",
          "Al Sailiya",
          "Al Sakhama",
          "Al Shagub",
          "Al-Shahaniya",
          "Al Souq",
          "Al Seej",
          "Al Tarfa",
          "Al Thakhira",
          "Al Themaid",
          "Al Thumama (Doha)",
          "Al Thumama (Al Wakrah)",
          "Umm Bab",
          "Umm Birka",
          "Umm Ghuwailina",
          "Umm Lekhba",
          "Umm Qarn",
          "Umm Salal Ali",
          "Umm Salal Mohammed",
          "Al Utouriya",
          "Wadi Al Banat",
          "Wadi Al Sail",
          "Wadi Al Wasaah",
          "Wadi Lusail",
          "Al Waab",
          "Al Wajba",
          "Al Wakrah",
          "Al Wukair",
          "Al Zubarah",
        ],
      },
      {
        name: "Saudi Arabia",
        cities: [
          "Abha",
          "Ad-Dilam",
          "Al-Abwa",
          "Al Artaweeiyah",
          "Al Bukayriyah",
          "Badr",
          "Baljurashi",
          "Bisha",
          "Bareq",
          "Buraydah",
          "Al Bahah",
          "Arar",
          "Dammam",
          "Dhahran",
          "Dhurma",
          "Dahaban",
          "Diriyah",
          "Duba",
          "Dumat Al-Jandal",
          "Dawadmi",
          "Farasan",
          "Gatgat",
          "Gerrha",
          "Ghawiyah",
          "Al-Gwei'iyyah",
          "Hautat Sudair",
          "Habaala",
          "Hajrah",
          "Haql",
          "Al-Hareeq",
          "Harmah",
          "Ha'il",
          "Hotat Bani Tamim",
          "Hofuf-Al-Mubarraz",
          "Huraymila",
          "Hafr Al-Batin",
          "Jabal Umm al Ru'us",
          "Jalajil",
          "Jeddah",
          "Jizan",
          "Jazan Economic City",
          "Jubail",
          "Al Jafr",
          "Irqah",
          "Khafji",
          "Khaybar",
          "King Abdullah Economic City",
          "Khamis Mushait",
          "King Khalid Military City",
          "Al-Saih",
          "Knowledge Economic City, Medina",
          "Khobar",
          "Al-Khutt",
          "Layla",
          "Lihyan",
          "Al Lith",
          "Al Majma'ah",
          "Mastoorah",
          "Al Mikhwah",
          "Al Mawain",
          "Medina",
          "Mecca",
          "Muzahmiyya",
          "Najran",
          "Al-Namas",
          "Neom",
          "Umluj",
          "Al-Omran",
          "Al-Oyoon",
          "Qadeimah",
          "Qatif",
          "Qaisumah",
          "Al Qunfudhah",
          "Qurayyat",
          "Rabigh",
          "Rafha",
          "Ar Rass",
          "Ras Tanura",
          "Rumah",
          "Raghbah",
          "Ranyah",
          "Riyadh",
          "Riyadh Al-Khabra",
          "Rumailah",
          "Sabt Al Alaya",
          "Sabya",
          "Sarat Abidah",
          "Saihat",
          "Safwa city",
          "Sakakah",
          "Sharurah",
          "Shaqra",
          "Shaybah",
          "As Sulayyil",
          "Taif",
          "Tabuk",
          "Tanomah",
          "Tarout",
          "Tayma",
          "Thadiq",
          "Thuwal",
          "Thuqbah",
          "Turaif",
          "Tabarjal",
          "Udhailiyah",
          "Al-'Ula",
          "Um Al-Sahek",
          "Unaizah",
          "Uqair",
          "Uyayna",
          "Uyun AlJiwa",
          "Wadi Al-Dawasir",
          "Al Wajh",
          "Yanbu",
          "Az Zaimah",
          "Zulfi",
        ],
      },
      {
        name: "United Arab Emirates",
        cities: [
          "Abu Dhabi",
          "Ajman",
          "Al Ain",
          "Dubai",
          "Fujairah",
          "Khor Fakkan",
          "Ras Al Khaimah",
          "Sharjah",
          "Umm Al Quwain",
          "Dibba Al-Fujairah",
          "Dibba Al-Hisn",
          "Kalba",
          "Jebel Ali",
          "Al Dhaid",
          "Madinat Zayed",
          "Ghayathi",
          "Liwa Oasis",
          "Al Awir",
          "Al Madam",
          "Al Manama",
        ],
      },
    ],

    loadTypes: [
      "Full Truckload (FTL)",
      "Less Than Truckload (LTL)",
      "Project Basis"
    ],

    testimonials: [
      {
        name: "Maya Rothwell",
        role: "Founder & CEO",
        company: "Open Ventures",
        quote:
          "Untitled's network helps us move loads efficiently with real‑time tracking and reliable partners. Posting a load takes seconds and responses are instant.",
        avatar: "https://i.pravatar.cc/100?img=47",
        rating: 5,
      },
      {
        name: "Arjun Mehta",
        role: "Operations Lead",
        company: "Delta Logistics",
        quote:
          "The matching quality is fantastic. We cut empty miles and improved on‑time performance across corridors.",
        avatar: "https://i.pravatar.cc/100?img=12",
        rating: 5,
      },
      {
        name: "Sarah Nguyen",
        role: "Supply Manager",
        company: "BrightSteel",
        quote:
          "Clean UI, fast carrier responses, and solid documentation. It became our team's default posting tool.",
        avatar: "https://i.pravatar.cc/100?img=5",
        rating: 4,
      },
      {
        name: "Diego Silva",
        role: "Procurement",
        company: "Rio Commodities",
        quote:
          "Scheduling and updates are seamless. The visibility features removed constant check‑in calls.",
        avatar: "https://i.pravatar.cc/100?img=23",
        rating: 5,
      },
    ],
  },

  assets: {
    appScreen: "https://images.unsplash.com/photo-1551650975-87deedd944c3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1074&q=80",
  },
};

// Legacy exports for backward compatibility
export const countries: CountryWithCities[] = POST_LOAD.data.countries;
export const COUNTRIES = POST_LOAD.data.countries.map((c) => c.name);
export const LOAD_TYPES = POST_LOAD.data.loadTypes;
export const APP_SCREEN = POST_LOAD.assets.appScreen;
export const POST_LOAD_TEXT = {
  form: POST_LOAD.form,
  sections: POST_LOAD.sections,
  labels: POST_LOAD.labels,
  placeholders: POST_LOAD.placeholders,
  ariaLabels: POST_LOAD.ariaLabels,
  alt: POST_LOAD.alt,
};
export const TESTIMONIALS: Testimonial[] = POST_LOAD.data.testimonials;

